---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-bank-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:firsttimeeagle-corp/simple-bank-gitops.git
    targetRevision: HEAD
    path: environments/staging/simple-bank
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true